-- seeds relaciones

DELETE FROM Compromisos_diarios CASCADE;
DELETE FROM Donaciones CASCADE;
DELETE FROM Localizacion CASCADE;
DELETE FROM Relaciones_interpersonales CASCADE;
DELETE FROM LOGRADO;
DELETE FROM FORMULARIO_INICIAL;

-- users

DELETE FROM USUARIOS CASCADE;
DELETE FROM CAT_SERVICIOS CASCADE;
DELETE FROM ORGANIZACIONES CASCADE;
DELETE FROM FORMULARIO_INICIAL CASCADE;
DELETE FROM Actividades_sustituciones CASCADE;
DELETE FROM Servicios CASCADE;
DELETE FROM Vacaciones CASCADE;
DELETE FROM Viajes CASCADE;
DELETE FROM Actividad_fisica CASCADE;
DELETE FROM HC0_calculo CASCADE;
DELETE FROM Logrado CASCADE;
DELETE FROM registro_huella_c CASCADE;