
-- seeds-direcciones
DELETE FROM DIRECCIONES CASCADE;

-- seeds 
DELETE FROM users CASCADE;
DELETE FROM ACTIVIDADES_REDUCCION CASCADE;
DELETE FROM alimentacion CASCADE;
DELETE FROM alojamiento CASCADE;
DELETE FROM calefaccion CASCADE;
DELETE FROM combustible CASCADE;
DELETE FROM deportes CASCADE;
DELETE FROM INICIATIVAS CASCADE;
DELETE FROM LOGROS CASCADE;
DELETE FROM transportes CASCADE;
DELETE FROM vehiculos CASCADE;
DELETE FROM tipo_vivienda CASCADE;